FROM ghcr.io/linuxserver/baseimage-alpine:arm32v7-3.16

# set version label
ARG BUILD_DATE
ARG KASM_VERSION
LABEL build_version="Linuxserver.io version:- ${VERSION} Build-date:- ${BUILD_DATE}"
LABEL maintainer="thelamer"

# add init files
COPY root-armhf/ /
