#!/usr/bin/with-contenv bash

# Wait for docker to be up
while [[ ! -S /var/run/docker.sock ]]; do
  sleep 1
done

# Don't do anything if wizard is disabled
if [[ -f "/opt/NO_WIZARD" ]]; then
    sleep infinity
fi

cd /wizard || exit 1
/usr/bin/node index.js
